// eslint-disable-next-line no-unused-vars
export const bestProducts = [
  {
    id: 21,
    brand: "Jordan",
    name: "Air Jordan 1 Mid",
    description: "",
    discount: 150,
    price: 125,
    url: "https://www.sneakersnstuff.com/images/365390/product_large.jpg",
    f: "https://www.sneakersnstuff.com/images/359874/product_large.jpg",
    b: "https://www.sneakersnstuff.com/images/359871/product_large.jpg",
    bt: "https://www.sneakersnstuff.com/images/359875/product_large.jpg",
  },
  {
    id: 22,
    brand: "Vans Vault",
    name: "OG Authentic LX",
    description: "",
    discount: 89,
    price: 69,
    url: "https://www.sneakersnstuff.com/images/264623/card_small.jpg",
    f: "https://www.sneakersnstuff.com/images/264624/product_large.jpg",
    b: "https://www.sneakersnstuff.com/images/264626/product_large.jpg",
    bt: "https://www.sneakersnstuff.com/images/264628/product_large.jpg",
  },
  {
    id: 23,
    brand: "Vans",
    name: "UA OG Sid LX",
    description: "",
    discount: 32,
    price: 25,
    url: "https://www.sneakersnstuff.com/images/278680/card_small.jpg",
    f: "https://www.sneakersnstuff.com/images/278676/product_large.jpg",
    b: "https://www.sneakersnstuff.com/images/278681/product_large.jpg",
    bt: "https://www.sneakersnstuff.com/images/278683/product_large.jpg",
  },
  {
    id: 24,
    brand: "Adidas",
    name: "Wmns Stan SB",
    description: "",
    discount: 132,
    price: 125,
    url: "https://www.sneakersnstuff.com/images/359569/card_small.jpg",
    f: "https://www.sneakersnstuff.com/images/359568/product_large.jpg",
    b: "https://www.sneakersnstuff.com/images/359566/product_large.jpg",
    bt: "https://www.sneakersnstuff.com/images/359570/product_large.jpg",
  },
  {
    id: 25,
    brand: "Nike Sport",
    name: "Air Force 1 '07 LX",
    description: "",
    discount: 135,
    price: 129,
    url: "https://www.sneakersnstuff.com/images/371756/card_small.jpg",
    f: "https://www.sneakersnstuff.com/images/371750/product_large.jpg",
    b: "https://www.sneakersnstuff.com/images/375557/product_large.jpg",
    bt: "https://www.sneakersnstuff.com/images/371751/product_large.jpg",
  },
  {
    id: 26,
    brand: "Puma",
    name: "Blaze of Glory P.",
    description: "",
    discount: 135,
    price: 129,
    url: "https://www.sneakersnstuff.com/images/375335/card_small.jpg",
    f: "https://www.sneakersnstuff.com/images/374004/product_large.jpg",
    b: "https://www.sneakersnstuff.com/images/374005/product_large.jpg",
    bt: "https://www.sneakersnstuff.com/images/375334/product_large.jpg",
  },
  {
    id: 27,
    brand: "Vans Vault",
    name: "OG Classic Slip-On LX",
    description: "",
    discount: 79,
    price: 69,
    url: "https://www.sneakersnstuff.com/images/266700/product_xlarge.jpg",
    f: "https://www.sneakersnstuff.com/images/266694/product_xlarge.jpg",
    b: "https://www.sneakersnstuff.com/images/266699/product_xlarge.jpg",
    bt: "https://www.sneakersnstuff.com/images/266701/product_xlarge.jpg",
  },
  {
    id: 28,
    brand: "Puma",
    name: "Blaze of Glory P.",
    description: "",
    discount: 135,
    price: 129,
    url: "https://www.sneakersnstuff.com/images/359874/product_large.jpg",
    f: "https://www.sneakersnstuff.com/images/359876/product_large.jpg",
    b: "https://www.sneakersnstuff.com/images/359871/product_large.jpg",
    bt: "https://www.sneakersnstuff.com/images/359875/product_large.jpg",
  },
];
// eslint-disable-next-line no-unused-vars
export const productList = [
  {
    id: 1,
    brand: "Jordan",
    name: "Jordan Graville Pro",
    description: "",
    discount: 142,
    price: 135,
    url: "https://www.sneakersnstuff.com/images/379983/card_medium.jpg",
    f: "https://www.sneakersnstuff.com/images/379984/product_large.jpg",
    b: "https://www.sneakersnstuff.com/images/379985/product_large.jpg",
    bt: "https://www.sneakersnstuff.com/images/379990/product_large.jpg",
  },
  {
    id: 2,
    brand: "Jordan",
    name: "Air Jordan 1 Mid",
    description: "",
    discount: 132,
    price: 125,
    url: "https://www.sneakersnstuff.com/images/365390/product_large.jpg",
    f: "https://www.sneakersnstuff.com/images/359874/product_large.jpg",
    b: "https://www.sneakersnstuff.com/images/359871/product_large.jpg",
    bt: "https://www.sneakersnstuff.com/images/359875/product_large.jpg",
  },
  {
    id: 3,
    brand: "Adidas",
    name: "Adimatic Mid YNuK",
    description: "",
    discount: 147,
    price: 140,
    url: "https://www.sneakersnstuff.com/images/379549/card_medium.jpg",
    f: "https://www.sneakersnstuff.com/images/379553/product_large.jpg",
    b: "https://www.sneakersnstuff.com/images/379554/product_large.jpg",
    bt: "https://www.sneakersnstuff.com/images/379551/product_large.jpg",
  },
  {
    id: 4,
    brand: "Adidas",
    name: "Adimatic YNuK",
    description: "",
    discount: 134,
    price: 130,
    url: "https://www.sneakersnstuff.com/images/379555/card_medium.jpg",
    f: "https://www.sneakersnstuff.com/images/379559/product_large.jpg",
    b: "https://www.sneakersnstuff.com/images/379560/product_large.jpg",
    bt: "https://www.sneakersnstuff.com/images/379557/product_large.jpg",
  },
  {
    id: 5,
    brand: "Adidas",
    name: "Campus 00s YNuK",
    description: "",
    discount: 132,
    price: 120,
    url: "https://www.sneakersnstuff.com/images/379561/card_medium.jpg",
    f: "https://www.sneakersnstuff.com/images/379564/product_large.jpg",
    b: "https://www.sneakersnstuff.com/images/379565/product_large.jpg",
    bt: "https://www.sneakersnstuff.com/images/379562/product_large.jpg",
  },
  {
    id: 6,
    brand: "Nike Sport",
    name: "Wmns AF 1 07 SE",
    description: "",
    discount: 120,
    price: 115,
    url: "https://www.sneakersnstuff.com/images/379046/card_medium.jpg",
    f: "https://www.sneakersnstuff.com/images/379048/product_large.jpg",
    b: "https://www.sneakersnstuff.com/images/379047/product_large.jpg",
    bt: "https://www.sneakersnstuff.com/images/379054/product_large.jpg",
  },
  {
    id: 7,
    brand: "Nike Sport",
    name: "Air Force 1 '07",
    description: "",
    discount: 114,
    price: 109,
    url: "https://www.sneakersnstuff.com/images/379514/card_medium.jpg",
    f: "https://www.sneakersnstuff.com/images/379510/product_large.jpg",
    b: "https://www.sneakersnstuff.com/images/379509/product_large.jpg",
    bt: "https://www.sneakersnstuff.com/images/379516/product_large.jpg",
  },
  {
    id: 8,
    brand: "Nike Sport",
    name: "Air Max 90",
    description: "",
    discount: 132,
    price: 129,
    url: "https://www.sneakersnstuff.com/images/379522/card_medium.jpg",
    f: "https://www.sneakersnstuff.com/images/379518/product_large.jpg",
    b: "https://www.sneakersnstuff.com/images/379517/product_large.jpg",
    bt: "https://www.sneakersnstuff.com/images/379524/product_large.jpg",
  },
  {
    id: 9,
    brand: "Jordan",
    name: "Wmns 1 Elevate Low",
    description: "",
    discount: 142,
    price: 135,
    url: "https://www.sneakersnstuff.com/images/378765/card_medium.jpg",
    f: "https://www.sneakersnstuff.com/images/378766/product_large.jpg",
    b: "https://www.sneakersnstuff.com/images/378767/product_large.jpg",
    bt: "https://www.sneakersnstuff.com/images/378768/product_large.jpg",
  },
  {
    id: 10,
    brand: "Nike",
    name: "Air Force 1'07 LX",
    description: "",
    discount: 132,
    price: 129,
    url: "https://www.sneakersnstuff.com/images/371756/card_medium.jpg",
    f: "https://www.sneakersnstuff.com/images/371750/product_large.jpg",
    b: "https://www.sneakersnstuff.com/images/375557/product_large.jpg",
    bt: "https://www.sneakersnstuff.com/images/371751/product_large.jpg",
  },
  {
    id: 11,
    brand: "Adidas",
    name: "Adimatic",
    description: "",
    discount: 109,
    price: 100,
    url: "https://www.sneakersnstuff.com/images/328562/card_medium.jpg",
    f: "https://www.sneakersnstuff.com/images/328561/product_large.jpg",
    b: "https://www.sneakersnstuff.com/images/328558/product_large.jpg",
    bt: "https://www.sneakersnstuff.com/images/328557/product_large.jpg",
  },
  {
    id: 12,
    brand: "Adidas",
    name: "Adimatic Red",
    description: "",
    discount: 134,
    price: 129,
    url: "https://www.sneakersnstuff.com/images/348890/card_medium.jpg",
    f: "https://www.sneakersnstuff.com/images/348891/product_large.jpg",
    b: "https://www.sneakersnstuff.com/images/348888/product_large.jpg",
    bt: "https://www.sneakersnstuff.com/images/348892/product_large.jpg",
  },
  {
    id: 13,
    brand: "Jordan",
    name: "AJ 1 Retro H OG",
    description: "",
    discount: 184,
    price: 179,
    url: "https://www.sneakersnstuff.com/images/375989/card_medium.jpg",
    f: "https://www.sneakersnstuff.com/images/375990/product_large.jpg",
    b: "https://www.sneakersnstuff.com/images/375994/product_large.jpg",
    bt: "https://www.sneakersnstuff.com/images/375991/product_large.jpg",
  },
  {
    id: 14,
    brand: "Jordan",
    name: "Jordan 1 Mid(GS)",
    description: "",
    discount: 114,
    price: 109,
    url: "https://www.sneakersnstuff.com/images/378722/card_medium.jpg",
    f: "https://www.sneakersnstuff.com/images/378723/product_large.jpg",
    b: "https://www.sneakersnstuff.com/images/378725/product_large.jpg",
    bt: "https://www.sneakersnstuff.com/images/378724/product_large.jpg",
  },
  {
    id: 15,
    brand: "Jordan",
    name: "Wmns Cortez SE",
    description: "",
    discount: 112,
    price: 99,
    url: "https://www.sneakersnstuff.com/images/378652/card_medium.jpg",
    f: "https://www.sneakersnstuff.com/images/378653/product_large.jpg",
    b: "https://www.sneakersnstuff.com/images/378654/product_large.jpg",
    bt: "https://www.sneakersnstuff.com/images/378659/product_large.jpg",
  },
  {
    id: 16,
    brand: "Nike",
    name: "Wmns AF 1'07 PRM",
    description: "",
    discount: 132,
    price: 129,
    url: "https://www.sneakersnstuff.com/images/378644/card_medium.jpg",
    f: "https://www.sneakersnstuff.com/images/378645/product_large.jpg",
    b: "https://www.sneakersnstuff.com/images/378646/product_large.jpg",
    bt: "https://www.sneakersnstuff.com/images/378647/product_large.jpg",
  },
  {
    id: 17,
    brand: "Adidas",
    name: "Campus 80 Crop",
    description: "",
    discount: 116,
    price: 110,
    url: "https://www.sneakersnstuff.com/images/378374/card_medium.jpg",
    f: "https://www.sneakersnstuff.com/images/378375/product_large.jpg",
    b: "https://www.sneakersnstuff.com/images/378376/product_large.jpg",
    bt: "https://www.sneakersnstuff.com/images/378377/product_large.jpg",
  },
  {
    id: 18,
    brand: "Converse",
    name: "Chuck T 70 Ox",
    description: "",
    discount: 82,
    price: 79,
    url: "https://www.sneakersnstuff.com/images/258686/card_medium.jpg",
    f: "https://www.sneakersnstuff.com/images/258681/product_large.jpg",
    b: "https://www.sneakersnstuff.com/images/258687/product_large.jpg",
    bt: "https://www.sneakersnstuff.com/images/258682/product_large.jpg",
  },
  {
    id: 19,
    brand: "Converse",
    name: "Chuck 70 Ox",
    description: "",
    discount: 89,
    price: 85,
    url: "https://www.sneakersnstuff.com/images/368565/card_medium.jpg",
    f: "https://www.sneakersnstuff.com/images/368568/product_large.jpg",
    b: "https://www.sneakersnstuff.com/images/368569/product_large.jpg",
    bt: "https://www.sneakersnstuff.com/images/368567/product_large.jpg",
  },
  {
    id: 20,
    brand: "Converse",
    name: "One Star Pro",
    description: "",
    discount: 79,
    price: 75,
    url: "https://www.sneakersnstuff.com/images/371163/card_medium.jpg",
    f: "https://www.sneakersnstuff.com/images/371160/product_large.jpg",
    b: "https://www.sneakersnstuff.com/images/371164/product_large.jpg",
    bt: "https://www.sneakersnstuff.com/images/371162/product_large.jpg",
  },
];
